apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverseproxy
  name: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: jugebhardt/reverseproxy:12890544398
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"   
        ports:
        - containerPort: 8080
      restartPolicy: Always