name: CICD

on:
  push:
    branches: [ "main" ]
    paths: 
       - 'udagram-api-feed/**'
       - 'udagram-api-user/**'
       - 'udagram-frontend/**'
       - 'udagram-reverseproxy/**'
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      
    - name: Remove unused and dangling images
      run: docker image prune --all
      
    - name: Build the Docker images
      run: docker compose -f docker-compose-build.yaml build --parallel
           
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Tag the Docker images
      run: |
           docker tag udagram-api-feed ${{ vars.DOCKERHUB_USERNAME }}/udagram-api-feed:${{ github.run_id }}
           docker tag udagram-api-user ${{ vars.DOCKERHUB_USERNAME }}/udagram-api-user:${{ github.run_id }} 
           docker tag udagram-frontend:local ${{ vars.DOCKERHUB_USERNAME }}/udagram-frontend:${{ github.run_id }}
           docker tag reverseproxy ${{ vars.DOCKERHUB_USERNAME }}/reverseproxy:${{ github.run_id }}
      
    - name: Push the Docker images
      run: |
           docker push ${{ vars.DOCKERHUB_USERNAME }}/udagram-api-feed:${{ github.run_id }}
           docker push ${{ vars.DOCKERHUB_USERNAME }}/udagram-api-user:${{ github.run_id }} 
           docker push ${{ vars.DOCKERHUB_USERNAME }}/udagram-frontend:${{ github.run_id }}
           docker push ${{ vars.DOCKERHUB_USERNAME }}/reverseproxy:${{ github.run_id }}
